services:
  - type: web
    name: object-detection-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn object_detection.wsgi:application
    workingDir: backend
