services:
  - type: web
    name: object-detection-backend
    runtime: python
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn object_detection.wsgi:application"
    pythonVersion: 3.10.13